
<div dir=rtl >
<h1>قوانین انجمنی</h1>

قوانین انجمنی روابط و وابستگی‌های متقابل بین مجموعه بزرگی از اقلام داده‌ای را نشان می‌دهند. 

مثال متداول در رابطه با کشف قوانین انجمنی "تحلیل سبد خرید" است.  در این فرایند با توجه به اقلام مختلفی که مشتریان در سبد خریدشان قرار می‌دهند، عادات و رفتار خرید مشتریان مورد تحلیل قرار می‌گیرد و می‌توان با شناسایی ارتباط بین محصولات، الگوهای تکرار شونده در حین خرید را بدست آورد.

سه پارامتر مهم:
- Support  میزان محبوبیت یک مجموعه آیتم را با توجه به دفعات حضور در تراکنش‌ها نشان می‌دهد.
- Confidence  احتمال خرید آیتم y در صورت خرید آیتم x را نشان می‌دهد. x -> y
- Lift   ترکیب دو پارامتر بالا می‌باشد.

برای پیاده سازی قوانین انجمنی در این تمرین، از الگوریتم Apriori که یکی از محبوب‌ترین و کارآمدترین الگوریتم‌های این حوزه است استفاده می‌کنیم.


<font color='Green'> پرسش:  تاثیر مقادیر مختلف پارامتر Lift را در احتمال وقوع نتیجه بررسی کنید.  </font>


</div>

<div dir=rtl >
پاسخ: 
لیفت یک معیار برای اندازه‌گیری همبستگی است که به شرح زیر ارائه می شود. وقوع مجموعه اقلام A مستقل از وقوع مجموعه اقلام B است
اگر

 P(A ∪ B) = P(A)P(B); در غیر این صورت، مجموعه آیتم های A و B به عنوان رویداد وابسته و همبسته هستند. این تعریف را می توان به راحتی به بیش از دو مجموعه آیتم تعمیم داد. میزان lift بین وقوع A و B را می توان با محاسبه اندازه گیری کرد:
lift(A,B)= P(A∪B) / P(A)P(B)

اگر مقدار lift کمتر از 1 باشد؛ وقوع A با وقوع B همبستگی منفی دارد، به این معنی که وقوع یکی به احتمال زیاد منجر به عدم وجود دیگری می شود. اگر مقدار lift بزرگتر از 1 باشد، A و B همبستگی مثبت دارند، به این معنی که وقوع یکی دلالت بر وقوع دیگری دارد. و اگر مقدار حاصل برابر با 1 باشد، A و B مستقل هستند و هیچ ارتباطی بین آنها وجود ندارد.

پس مقدار بالای lift  ارتباط مثبت زیاد دو آیتم را نشان می‌دهد و مقدار کم lift  ارتباط ضعیف آن دو را!
  
</div>


<div dir=rtl >
<h1>الگوریتم Apriori</h1>

روش کار الگوریتم به این صورت است که یک  حداقل مقدار پشتیبانی در نظر گرفته    می‌شود و تکرارها با مجموعه آیتم‌های مکرر اتفاق می‌افتند. در صورتیکه  مجموعه‌ها و زیرمجموعه‌ها مقدار پشتیبانی کمتر از حد آستانه داشته باشند حذف می‌شوند. این روند تا زمانیکه امکان حذف وجود نداشته باشد ادامه می‌یابد. 

در این بخش از تمرین می‌خواهیم الگوریتم apriori را بر روی مجموعه داده Hypermarket_dataset که شامل سفارشات خرید افراد از فروشگاه های مواد غذایی است اعمال کنیم.


</div>


<div dir=rtl >
<h1>آماده‌سازی داده</h1>

<font color='Green'>پرسش: برای شروع کار باید داده‌های دیتاست را در قالب ماتریس پراکنده که محصولات  خریداری شده در ستون‌ و شماره سفارشات خرید به عنوان شاخص (index) هستند آماده کنید. 


برای راحتی کار محصولات خریداری شده در هر سفارش را با اعداد 0,1 کدگذاری کنید.

 نمونه ماتریس خروجی شما:

<img src="https://drive.google.com/uc?id=1eD0jan1ZbeYqSklgK--ks7oeY-MyTA3p"></img>

</div>

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
 
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [25]:
# your code here
# ...

dataset = pd.read_csv("Hypermarket_dataset.csv", header = None)
dataset.iloc[1: , :]

columns = []
j = 0
for i in dataset.iloc[:, 2]:
  if j == 0:
    j+=1
    continue
  temp_columns = i
  columns += [temp_columns]
columns = list(set(columns)) # remove redundant columns

transaction_dict = {}
i = 0
for index, row in dataset.iterrows():
  if i == 0:
    i+=1
    continue
  index = row[0]
  items = row[2]
  if index in transaction_dict:
    transaction_dict[index] += [items]
  else:
    transaction_dict[index] = [] 
    transaction_dict[index] += [items]

matrix = []
for key, value in transaction_dict.items():
  new_item_list = [0]*len(columns)
  for temp_val in value:
    new_item_list[columns.index(temp_val)] = 1
  matrix.append(new_item_list)

# print(transaction_dict['1000'])

indexes = list(transaction_dict.keys())
output_dataframe = pd.DataFrame(matrix, index=indexes, columns=columns)
output_dataframe.sort_index()

,spices,canned fish,vinegar,salad dressing,butter milk,tea,male cosmetics,liqueur,frozen fish,finished products,...,rum,syrup,organic sausage,canned beer,potato products,chewing gum,cling film/bags,frozen fruits,butter,cream cheese
1000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1002,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4999,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


<div dir=rtl >
<h1>شناسایی الگوهای پر تکرار</h1>

<font color='Green'> پرسش:  با اعمال الگوریتم apriori و به ازای مقدار min_support = 0.07 تمامی الگوهای پر تکرار را تولید نمایید. 

</div>

In [36]:
# your code here
# ...
frequent_itemsets = apriori(output_dataframe, min_support=0.07, use_colnames=True)
frequent_itemsets['k-freq'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
# frequent_itemsets = frequent_itemsets.sort_values('support')
frequent_itemsets

     support                                    itemsets  k-freq
0   0.177527                                    (pastry)       1
1   0.133145                             (domestic eggs)       1
2   0.168291                             (shopping bags)       1
3   0.079785                                   (berries)       1
4   0.158799                              (bottled beer)       1
..       ...                                         ...     ...
78  0.090816               (root vegetables, rolls/buns)       2
79  0.079271                 (rolls/buns, bottled water)       2
80  0.082350                       (rolls/buns, sausage)       2
81  0.071832      (other vegetables, yogurt, whole milk)       3
82  0.082093  (other vegetables, rolls/buns, whole milk)       3

[83 rows x 3 columns]


<div dir=rtl >
<h1>استخراج قوانین انجمنی</h1>


<font color='Green'> پرسش: تابعی بنویسید که با گرفتن دو ورودی confidence و lift قوانین انجمنی حاصل را در خروجی نشان دهد. </br>
برای دو حالت خروجی خود را در گزارش ثبت کنید.


</div>

In [42]:
# your code here
# ...

def extract_rules(confidence_or_lift, amount):
  rules = association_rules(frequent_itemsets, metric=confidence_or_lift, min_threshold=amount)
  if confidence_or_lift == 'lift':
    rules = rules.sort_values("lift",ascending=False)
  else:
    rules = rules.sort_values("confidence",ascending=False)

  return rules

In [43]:
extract_rules('confidence', 0.07)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
86,"(other vegetables, yogurt)",(whole milk),0.120318,0.458184,0.071832,0.597015,1.303003,0.016704,1.344507
92,"(other vegetables, rolls/buns)",(whole milk),0.146742,0.458184,0.082093,0.559441,1.220996,0.014859,1.229837
8,(shopping bags),(whole milk),0.168291,0.458184,0.091329,0.542683,1.184422,0.014220,1.184772
10,(bottled beer),(whole milk),0.158799,0.458184,0.085428,0.537964,1.174124,0.012669,1.172672
32,(yogurt),(whole milk),0.282966,0.458184,0.150590,0.532185,1.161510,0.020940,1.158185
...,...,...,...,...,...,...,...,...,...
97,(whole milk),"(other vegetables, rolls/buns)",0.458184,0.146742,0.082093,0.179171,1.220996,0.014859,1.039508
49,(whole milk),(whipped/sour cream),0.458184,0.154695,0.079785,0.174132,1.125650,0.008906,1.023536
50,(whole milk),(newspapers),0.458184,0.139815,0.072345,0.157895,1.129310,0.008284,1.021469
91,(whole milk),"(other vegetables, yogurt)",0.458184,0.120318,0.071832,0.156775,1.303003,0.016704,1.043235
4,(whole milk),(domestic eggs),0.458184,0.133145,0.070292,0.153415,1.152242,0.009287,1.023944

In [44]:
extract_rules('lift', 1.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
6,(yogurt),"(other vegetables, whole milk)",0.282966,0.191380,0.071832,0.253853,1.326434,0.017678,1.083727
3,"(other vegetables, whole milk)",(yogurt),0.191380,0.282966,0.071832,0.375335,1.326434,0.017678,1.147870
7,(whole milk),"(other vegetables, yogurt)",0.458184,0.120318,0.071832,0.156775,1.303003,0.016704,1.043235
2,"(other vegetables, yogurt)",(whole milk),0.120318,0.458184,0.071832,0.597015,1.303003,0.016704,1.344507
1,(sausage),(yogurt),0.206003,0.282966,0.075423,0.366127,1.293892,0.017132,1.131196
0,(yogurt),(sausage),0.282966,0.206003,0.075423,0.266546,1.293892,0.017132,1.082545
5,(other vegetables),"(yogurt, whole milk)",0.376603,0.150590,0.071832,0.190736,1.266589,0.015119,1.049608
4,"(yogurt, whole milk)",(other vegetables),0.150590,0.376603,0.071832,0.477002,1.266589,0.015119,1.191967
9,"(other vegetables, whole milk)",(rolls/buns),0.191380,0.349666,0.082093,0.428954,1.226753,0.015174,1.138847
12,(rolls/buns),"(other vegetables, whole milk)",0.349666,0.191380,0.082093,0.234776,1.226753,0.015174,1.056710
8,"(other vegetables, rolls/buns)",(whole milk),0.146742,0.458184,0.082093,0.559441,1.220996,0.014859,1.229837
13,(whole milk),"(other vegetables, rolls/buns)",0.458184,0.146742,0.082093,0.179171,1.220996,0.014859,1.039508
10,"(rolls/buns, whole milk)",(other vegetables),0.178553,0.376603,0.082093,0.459770,1.220834,0.014850,1.153947
11,(other vegetables),"(rolls/buns, whole milk)",0.376603,0.178553,0.082093,0.217984,1.220834,0.014850,1.050422